/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package charts;

import charts.service.InsuranceService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Running Charts Server!";
    }


    private static InsuranceService insuranceService;

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SpringApplication.run(App.class, args);

    }
}
